---
services: docker

env:
  - distro: geerlingguy/docker-centos6-ansible:latest
    init: /sbin/init
    run_opts: "--privileged"
  - distro: geerlingguy/docker-centos7-ansible:latest
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: williamyeh/ansible:debian7
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: geerlingguy/docker-debian8-ansible:latest
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: geerlingguy/docker-ubuntu1204-ansible:latest
    init: /sbin/init
    run_opts: "--privileged"
  - distro: geerlingguy/docker-ubuntu1404-ansible:latest
    init: /sbin/init
    run_opts: "--privileged"
  - distro: geerlingguy/docker-ubuntu1604-ansible:latest
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  # Pull container.
  - 'sudo docker pull ${distro}'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} ${distro} "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

#notifications:
#  email: false
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
# sudo docker exec --tty "e2e29a1cec113371952d8c4a69f0335d1fdbe2672227f06f9a48dad28abaaf19" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml