---
services: docker

env:
#  - distro: centos6
#  - distro: centos7

  - { distro: debian8,    role: test_java7 }
  - { distro: ubuntu1204, role: test_java7 }
  - { distro: ubuntu1404, role: test_java7 }
  - { distro: ubuntu1604, role: test_java7 }
  - { distro: centos7,    role: test_java7 }

  - { distro: debian8,    role: test_java8 }
  - { distro: ubuntu1204, role: test_java8 }
  - { distro: ubuntu1404, role: test_java8 }
  - { distro: ubuntu1604, role: test_java8 }
  - { distro: centos7,    role: test_java8 }

script:
  - './test.sh -p -i -s -r ${role} -o ${distro}'

notifications:
  email: false
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/