---
services: docker

env:
  - distro: centos6
  - distro: centos7
  - distro: debian8
#  - distro: ubuntu1204
#  - distro: ubuntu1404
  - distro: ubuntu1604

script:
  - './test.sh -p -r -i -s -d ${distro}'

notifications:
  email: false
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/