---
- name: Install firefox from package
  package: name=firefox state=present
  when: selenium_firefox_install_mode == 'package'



- name: Check firefox version
  shell: firefox --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: firefox_version_result
  changed_when: false

- fail: msg="Firefox version is not compatible with selenium version."
  when: firefox_version_result.stdout|int > 47 and selenium_server_version[0:1] == '2'
  changed_when: false

- fail: msg="Firefox version is not compatible with selenium version."
  when: firefox_version_result.stdout|int < 48 and selenium_server_version[0:1] == '3'
  changed_when: false

#- name: Download and install GeckoDriver
#  unarchive:
#    src: "{{ selenium_geckodriver_download_url }}"
#    dest: "{{ selenium_geckodriver_install_path }}"
#    copy: no
#
#- file:
#    path: "{{ selenium_geckodriver_install_path }}/geckodriver"
#    owner: root
#    group: root
#    mode: 0755
#    state: file