---
######################################################################
###############             PACKAGE                   ################
######################################################################

# @todo check for firefox installed

- name: Install firefox from package
  package: name=firefox state=present

######################################################################
###############             COMPATIBILITY             ################
######################################################################

- name: Check firefox version
  shell: firefox --version | sed 's/[^0-9.]*\([0-9]*\).*/\1/'
  register: firefox_version_result
  changed_when: false
  tags: [test]

- fail: msg="Firefox {{ firefox_version_result.stdout }} is not compatible with Selenium 2. Use 47 or lower"
  when: firefox_version_result.stdout|int > 47 and selenium_server_version[0:1] == '2'
  changed_when: false
  tags: [test]

- fail: msg="Firefox {{ firefox_version_result.stdout }} is not compatible with Selenium 3. Use 48 or lower"
  when: firefox_version_result.stdout|int < 48 and selenium_server_version[0:1] == '3'
  changed_when: false
  tags: [test]

######################################################################
###############             GECKODRIVER               ################
######################################################################

- block:
  - name: Download and install GeckoDriver
    unarchive:
      src: "{{ selenium_geckodriver_download }}"
      dest: "{{ selenium_geckodriver_dir }}"
      copy: no
      creates: "{{ selenium_geckodriver_dir }}/geckodriver"

  - file:
      path: "{{ selenium_geckodriver_dir }}/geckodriver"
      owner: root
      group: root
      mode: 0755
      state: file
  when: selenium_server_version[0:1] == '3'