---
- set_fact:
    selenium_java_version: 7
  when: selenium_server_version[0:1] == '2'

- set_fact:
    selenium_java_version: 8
  when: selenium_server_version[0:1] == '3'

- include: firefox.yml
- include: selenium.yml