---
- set_fact:
    selenium_install_geckodriver: no
    selenium_java_version: 7
  when: selenium_server_version[0:1] == '2'

- set_fact:
    selenium_install_geckodriver: yes
    selenium_java_version: 8
  when: selenium_server_version[0:1] == '3'

- set_fact:
    selenium_xvfb_package: xvfb
  when: ansible_os_family == 'Debian'

- set_fact:
    selenium_xvfb_package: xorg-x11-server-Xvfb
  when: ansible_os_family == 'RedHat'

- include: firefox.yml
#- include: chrome.yml
- include: selenium.yml