---
# Most of the stuff here is monkey patching depdendencies. Sometimes to make sure the correct java packages are avialable
# or other missing packages

# set some vars based on selenium server version
- set_fact:
    selenium_java_version: 7
  when: selenium_server_version[0:1] == '2'
- set_fact:
    selenium_java_version: 8
  when: selenium_server_version[0:1] == '3'

- name: Include OS-Specific variables
  include_vars: "../../../vars/{{ ansible_os_family }}.yml"
  tags: [configuration, selenium]

# monkey patch for external java role to be able to install both java versions
# @todo: fix java role
- name: Add ubuntu ppa for installing different openjdk versions
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == 'Ubuntu'

- name: Add debian ppa for installing openjdk 8
  apt_repository: repo='deb http://ftp.debian.org/debian jessie-backports main' state=present
  when: selenium_server_version[0:1] == '3' and ansible_distribution == 'Debian'






# unzip is needed to extract the geckodriver when selenium >= 3
# @todo move to geckodriver install
#- name: Install unzip
#  package: name=unzip state=present update_cache=yes
#  when: selenium_server_version[0:1] == '3'

# bzip2 is needed by the external firefox role when firefox install mode is "archive"
# @todo calculate archive or package mode
# @todo: fix firefox role
#- name: Install bzip2
#  package: name=bzip2 state=present update_cache=yes
#  when: selenium_firefox_install_mode == 'archive'

#- name: Install gtk3 if firefox > 45
#  package: name=bzip2 state=present
#  when:
#      - ansible_os_family == 'RedHat'
#      - selenium_firefox_install_version|int > 45
