---
# set some vars based on selenium and os versions
- set_fact:
    selenium_java_version: 7
    selenium_install_geckodriver: no
  when: selenium_server_version[0:1] == '2'

- set_fact:
    selenium_java_version: 8
    selenium_install_geckodriver: yes
  when: selenium_server_version[0:1] == '3'

- include_vars: "../../../vars/{{ ansible_os_family }}.yml"

# monkey patch for external java role to be able to install both java versions
- name: Add ubuntu ppa for installing different openjdk versions
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == 'Ubuntu'

- name: Add debian ppa for installing openjdk 8
  apt_repository: repo='deb http://ftp.debian.org/debian jessie-backports main' state=present
  when: selenium_server_version[0:1] == '3' and ansible_distribution == 'Debian'

# install dependencies
- name: Install xvfb
  package: name={{ selenium_xvfb_package }} state=present
